---
name: File-StatCache
version: 0.04
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: a caching wrapper around the C<stat()> function
license: perl
provides:
  File::StatCache:
    file: lib/File/StatCache.pm
    version: 0.04
generated_by: Module::Build version 0.26
